In [ ]:
from ipymlwidgets.widgets import Canvas
from ipymlwidgets.utils import demo_image
import numpy as np

image = demo_image()
canvas = Canvas(width=image.shape[1], height=image.shape[0])
canvas.observe(print, "client_size")
canvas.css_width = "10%"
canvas.css_height = "auto"

canvas.set_image(image)
patch = np.full((10, 10, 4), [255, 0, 0, 255], dtype=np.uint8)
canvas.set_patch(25, 5, 10, 10, patch)
display(canvas)

import random
import ipywidgets as W
import time

def update_and_draw_random_patch(b):   

    #with canvas.hold():
    for i in range(2):
        
        # Draw a random colored patch at random position
        patch_size = random.randint(5, 15)
        x = random.randint(0, canvas.width - patch_size)
        y = random.randint(0, canvas.height - patch_size)
        
        # Random color
        color = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255), 255]
        patch = np.full((patch_size, patch_size, 4), color, dtype=np.uint8)
        
        canvas.set_patch(x, y, patch_size, patch_size, patch)
        print(f"Drew {patch_size}x{patch_size} patch at ({x}, {y}) with color {color[:3]}")
        
# Create the button
update_button = W.Button(description="Update & Draw Random Patch")
update_button.on_click(update_and_draw_random_patch)

display(update_button)

canvas.observe(print, "mouse_enter")
canvas.observe(print, "mouse_leave")
canvas.observe(print, "mouse_click")
canvas.observe(print, "mouse_drag")
canvas.observe(print, "mouse_down")
canvas.observe(print, "mouse_up")


In [ ]:
from ipymlwidgets.widgets import Image
from ipymlwidgets.utils import demo_image
import numpy as np

image = demo_image()
widget = Image(image)
widget[10:20, 10:20] = [255, 0, 0, 255]
widget.css_width = "20%"
widget.css_height = "auto"

image = np.ones_like(image) * np.array([255, 0, 0, 255], dtype=np.uint8)

widget.set_image(image, layer=0)
display(widget)

In [ ]:
from ipymlwidgets.widgets import Canvas
from ipymlwidgets.utils import demo_image
import numpy as np

image = demo_image()
canvas = Canvas(width=image.shape[1], height=image.shape[0], layers=2)

image[...,-1] = 100
image = np.random.randint(0, 255, image.shape, dtype=np.uint8)
image[...,-1] = 100

canvas.set_image(np.ones_like(image) * np.array([255, 0, 0, 255], dtype=np.uint8), layer=0)
canvas.set_image(image, layer=1)

canvas.css_width = "50%"
canvas.css_height = "auto"


display(canvas)

canvas.observe(print, "mouse_click")

canvas.stroke_color = "black"
canvas.stroke_width = 2
canvas.draw_rect(np.array([[10, 10, 20, 20]]))




In [ ]:
from ipymlwidgets.widgets import ImageOCR
from ipymlwidgets.utils import demo_image
import numpy as np

image = demo_image()
image_ocr = ImageOCR(image, boxes=np.array([[0,0, 20, 20]]), texts=["Hello"])
image_ocr.image_widget.css_width = "50%"

display(image_ocr)

In [1]:
from ipymlwidgets.widgets import ImageAnnotated
from ipymlwidgets.utils import demo_image
from PIL import Image 
import numpy as np
import ipywidgets as W

image = np.array(Image.fromarray(demo_image()).resize((512,512)))
print(image.shape)
image = demo_image()
widget = ImageAnnotated(image, boxes=np.array([[0,0, 8, 8]]), texts=["Hello"])
widget.css_width = "40%"
display(widget)

message = W.HTML(value="")
def update_message(x):  
    message.value = f"{x['new']}"
widget.observe(update_message, "selection")
display(message)
widget.observe(lambda x: print(x['new']), "boxes")

(512, 512, 4)


MultiCanvas((32, 32), layers=3)

HTML(value='')

client_size: 305, 307
stroke: 3
[0 0 8 8] 7 7
[7] [1] [7] [1]
inside [ True]
[False] [ True] [False] [ True]
[[0 0 8 8]]
[0 0 8 8] 7 7
[7] [1] [7] [1]
inside [ True]
[False] [ True] [False] [ True]
[[ 0  0 17 17]]
[ 0  0 17 17] 14 14
[14] [3] [14] [3]
inside [ True]
[False] [ True] [False] [ True]
[[ 0  0 10 12]]
[ 0  0 10 12] 4 9
[4] [6] [9] [3]
inside [ True]
[False] [False] [False] [ True]
[[ 0  0 10 21]]
[ 0  0 10 21] 5 9
[5] [5] [9] [12]
inside [ True]
[False] [False] [False] [False]
[[14  3 24 24]]
[14  3 24 24] 18 12
[4] [6] [9] [12]
inside [ True]
[False] [False] [False] [False]
[[ 5  5 15 26]]
[ 5  5 15 26] 13 13
[8] [2] [8] [13]
inside [ True]
[False] [ True] [False] [False]
[[ 5  5 26 26]]
[ 5  5 26 26] 11 7
[6] [15] [2] [19]
inside [ True]
[False] [False] [ True] [False]
[[ 5 16 26 26]]
[ 5 16 26 26] 14 21
[9] [12] [5] [5]
inside [ True]
[False] [False] [False] [False]
[[ 0  0 21 10]]
