In [ ]:
from ipymlwidgets.widgets import Canvas
from ipymlwidgets.utils import demo_image
import numpy as np

image = demo_image()
canvas = Canvas(width=image.shape[1], height=image.shape[0])
canvas.observe(print, "client_size")
canvas.css_width = "10%"
canvas.css_height = "auto"

canvas.set_image(image)
patch = np.full((10, 10, 4), [255, 0, 0, 255], dtype=np.uint8)
canvas.set_patch(25, 5, 10, 10, patch)
display(canvas)

import random
import ipywidgets as W
import time

def update_and_draw_random_patch(b):   

    #with canvas.hold():
    for i in range(2):
        
        # Draw a random colored patch at random position
        patch_size = random.randint(5, 15)
        x = random.randint(0, canvas.width - patch_size)
        y = random.randint(0, canvas.height - patch_size)
        
        # Random color
        color = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255), 255]
        patch = np.full((patch_size, patch_size, 4), color, dtype=np.uint8)
        
        canvas.set_patch(x, y, patch_size, patch_size, patch)
        print(f"Drew {patch_size}x{patch_size} patch at ({x}, {y}) with color {color[:3]}")
        
# Create the button
update_button = W.Button(description="Update & Draw Random Patch")
update_button.on_click(update_and_draw_random_patch)

display(update_button)

canvas.observe(print, "mouse_enter")
canvas.observe(print, "mouse_leave")
canvas.observe(print, "mouse_click")
canvas.observe(print, "mouse_drag")
canvas.observe(print, "mouse_down")
canvas.observe(print, "mouse_up")


In [ ]:
from ipymlwidgets.widgets import Image
from ipymlwidgets.utils import demo_image
import numpy as np

image = demo_image()
widget = Image(image)
widget[10:20, 10:20] = [255, 0, 0, 255]
widget.css_width = "20%"
widget.css_height = "auto"

image = np.ones_like(image) * np.array([255, 0, 0, 255], dtype=np.uint8)

widget.set_image(image, layer=0)
display(widget)

In [ ]:
from ipymlwidgets.widgets import Canvas
from ipymlwidgets.utils import demo_image
import numpy as np

image = demo_image()
canvas = Canvas(width=image.shape[1], height=image.shape[0], layers=2)

image[...,-1] = 100
image = np.random.randint(0, 255, image.shape, dtype=np.uint8)
image[...,-1] = 100

canvas.set_image(np.ones_like(image) * np.array([255, 0, 0, 255], dtype=np.uint8), layer=0)
canvas.set_image(image, layer=1)

canvas.css_width = "50%"
canvas.css_height = "auto"


display(canvas)

canvas.observe(print, "mouse_click")

canvas.stroke_color = "black"
canvas.stroke_width = 2
canvas.draw_rect(np.array([[10, 10, 20, 20]]))




In [ ]:
from ipymlwidgets.widgets import ImageOCR
from ipymlwidgets.utils import demo_image
import numpy as np

image = demo_image()
image_ocr = ImageOCR(image, boxes=np.array([[0,0, 20, 20]]), texts=["Hello"])
image_ocr.image_widget.css_width = "50%"

display(image_ocr)

In [2]:
from ipymlwidgets.widgets import ImageAnnotated
from ipymlwidgets.utils import demo_image
from PIL import Image 
import numpy as np
import ipywidgets as W

image = np.array(Image.fromarray(demo_image()).resize((512,512)))
print(image.shape)
widget = ImageAnnotated(image, boxes=np.array([[0,0, 8,8]]), texts=["Hello"])
widget.css_width = "100%"
display(widget)

message = W.HTML(value="")
def update_message(x):  
    message.value = f"{x['new']}"
widget.observe(update_message, "mouse_drag")
display(message)
widget.observe(lambda x: print(x['new']), "boxes")

(512, 512, 4)


MultiCanvas((512, 512), layers=3)

HTML(value='')

[0 0 8 8] 97 74
[97] [-89] [74] [-66]
inside [False]
[[  0   0   8   8]
 [ 97  74 207 178]]
[0 0 8 8] 102 171
[102   5] [-94 105] [171  97] [-163    7]
inside [False  True]
[False  True] [False False] [False False] [False  True]
[[  0   0   8   8]
 [110  74 207 118]]
[0 0 8 8] 116 82
[116   6] [-108   91] [82  8] [-74  36]
inside [False  True]
[False  True] [False False] [False  True] [False False]
[[  0   0   8   8]
 [ 60  47 207 118]]
[0 0 8 8] 202 53
[202 142] [-194    5] [53  6] [-45  65]
inside [False  True]
[False False] [False  True] [False  True] [False False]
[[  0   0   8   8]
 [ 60  68 181 118]]
[0 0 8 8] 176 112
[176 116] [-168    5] [112  44] [-104    6]
inside [False  True]
[False False] [False  True] [False False] [False  True]
[[  0   0   8   8]
 [ 60  68 246 203]]
[0 0 8 8] 241 116
[241 181] [-233    5] [116  48] [-108   87]
inside [False  True]
[False False] [False  True] [False False] [False False]
[[  0   0   8   8]
 [ 60  68 202 203]]
